<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Query-fp_psc-:-2MASS-All-Sky-Point-Source-Catalog-(PSC)" data-toc-modified-id="Query-fp_psc-:-2MASS-All-Sky-Point-Source-Catalog-(PSC)-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Query fp_psc : 2MASS All-Sky Point Source Catalog (PSC)</a></span></li><li><span><a href="#Checking-Accuracy" data-toc-modified-id="Checking-Accuracy-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Checking Accuracy</a></span><ul class="toc-item"><li><span><a href="#Comparing-to-GAIA" data-toc-modified-id="Comparing-to-GAIA-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Comparing to GAIA</a></span></li><li><span><a href="#Comparing-to-MNRAS-paper" data-toc-modified-id="Comparing-to-MNRAS-paper-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Comparing to MNRAS paper</a></span></li></ul></li></ul></div>

In [1]:
import numpy as np
import pandas as pd
from astropy import units as u
from astropy.coordinates import SkyCoord

In [2]:
##main_dir = "/Volumes/LaCie/Research/NAC/"
main_dir = "/u/kaimibk/Documents/Research/NAC/"
data_dir = main_dir+"data/"
out_dir = main_dir+"output/"

In [3]:
df = pd.read_csv(data_dir+"MN_17_3616_point.csv",
                index_col = 0)

In [4]:
df.head(4)

,Name,RA,Dec,K2MASS,(V-K)o,Period,Ref,BCK,logL/Lo,M/Mo,...,teff_val,teff_percentile_lower,teff_percentile_upper,radius_sigma,lum_sigma,teff_sigma,sinI_s,sinI_s_sigma,V,V_sigma
0,J03394633+2358531,54.943067,23.981442,11.83,4.89,1.138,1,2.73,-1.66,0.41,...,3562.0,3213.67,3929.82,NaN,NaN,358.077,NaN,NaN,NaN,NaN
1,J03414664+2301198,55.444367,23.022186,13.16,5.63,0.294,1,2.81,-2.23,0.19,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,J03414895+2303235,55.453963,23.056539,13.19,6.09,0.239,1,2.86,-2.26,0.19,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,J03415671+2358434,55.486317,23.978728,13.25,5.76,0.401,1,2.82,-2.27,0.18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
##c = SkyCoord(ra = df.RA, dec = df.Dec, unit=(u.deg, u.deg))

## Query fp_psc : 2MASS All-Sky Point Source Catalog (PSC)

In [6]:
from astroquery.irsa import Irsa

In [7]:
features = [
            "j_m", "j_msigcom", 
            "h_m", "h_msigcom",
            "k_m", "k_msigcom"
           ]
from astropy.coordinates import match_coordinates_sky

def retrieve(idx, df):
    global features
    global c
    temp = Irsa.query_region(c[idx], 
                     radius=5*u.arcsecond,
                    catalog="fp_psc").to_pandas()
    
    catalog = SkyCoord(ra=temp.ra, dec=temp.dec,
                       unit=(u.deg, u.deg))
    
    i,_,_ = match_coordinates_sky(c[idx], catalog)
    
    for feat in features:
        df.at[idx, feat] = temp.at[int(i), feat]

In [8]:
[retrieve(i, df) for i, row in df.iterrows()]

[None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None]

In [31]:
df_trim = df[["RA", "Dec", 
              "parallax", "parallax_error",
              "j_m", "j_msigcom",
              "h_m", "h_msigcom",
              "k_m", "k_msigcom", "Name"
             ]]

In [33]:
df_trim["band"] = "kmag"

/Users/kaimibk/miniconda3/envs/UHenv/lib/python3.6/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

In [36]:
df_trim[["RA", "Dec", 
              "parallax"*10**(-3), "parallax_error"*10**(-3),
              "j_m", "j_msigcom",
              "h_m", "h_msigcom",
              "k_m", "k_msigcom", "band", "Name"
             ]].to_csv(main_dir+"MN_17_3616_gaia2.csv")

In [7]:
import sys
import os
#sys.path.append("/Users/kaimibk/Documents/Research/isoclassify/")
#sys.path.append("/u/kaimibk/Documents/scripts/isoclassify/")
#from isoclassify import *

SyntaxError: invalid syntax (isoclassify.py, line 151)

In [8]:
df_trim = pd.read_csv(main_dir+"MN_17_3616_gaia2.csv",
                        index_col = 0)

In [9]:
for i in range(len(df)):
    out_dir = main_dir+"/output/{}/".format(df_trim.loc[i].comments)
    
    if os.path.isdir(out_dir) == False:
        os.makedirs(out_dir)
    
    if os.path.isfile(out_dir+"output.csv"):
        df2 = pd.read_csv(out_dir+"output.csv")

        df.at[i, "iso_rad"] = float(df2.loc[df2['id_starname'] == 'dir_rad'][str(i)].values)
        df.at[i, "iso_rad_Err"] = float(df2.loc[df2['id_starname'] == 'dir_rad_err1'][str(i)].values)    
    else:
        kwargs={'method': 'direct', 
                'id_starname': i, 
                'csv': main_dir+'MN_17_3616_gaia2.csv', 
                'outdir': out_dir, 'dust': 'allsky'}
        run(**kwargs);
    
        df2 = pd.read_csv(out_dir+"output.csv")
        df2.columns = range(len(columns))

        df.at[i, "iso_rad"] = float(df2.loc[df2['id_starname'] == 'dir_rad'][str(i)].values)
        df.at[i, "iso_rad_Err"] = float(df2.loc[df2['id_starname'] == 'dir_rad_err1'][str(i)].values)

In [11]:
df.to_csv(main_dir+"Pleiades_G_2M_I.csv")